version: "3.8"

services:
    test-node-16:
        image: node:16-alpine
        volumes:
            - .:/app
        working_dir: /app
        command: npm test

    test-node-18:
        image: node:18-alpine
        volumes:
            - .:/app
        working_dir: /app
        command: npm test

    test-node-20:
        image: node:20-alpine
        volumes:
            - .:/app
        working_dir: /app
        command: npm test
